/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appDoesNotThrow() {
        assertDoesNotThrow(() -> new App());
    }
}
